### ISSUE TITLE
Multiple IG and Map API calls per request

### ISSUE THREAD

**Issue by carterchung** [TeamKraken/Instatrip#58]
As evidenced by console logs. 
getPhoto called by ourCallback, which is called by calcRoute, which is called every time getmap is called. getmap is called by makeMap, which is called every time there is a state change start, which encompasses any navigation between states
![image](https://cloud.githubusercontent.com/assets/8279692/8835219/f2291e50-306d-11e5-82d8-e84c6b7d6fec.png)

**Comment by Mavmeister** [comment]
Fixed by Carter. Moved code into module.
